services:
  vehicle_service_app:
    build:
      context: ../VehicleService  
      dockerfile: Dockerfile
      target: build    
    
    volumes:
      - ../VehicleService:/app 
      - ~/.nuget/packages:/root/.nuget/packages:ro

    command: ["dotnet", "watch", "run", "--urls", "http://+:8080"]

    environment:
      ASPNETCORE_ENVIRONMENT: Development


  user_service_app:
    build:
      context: ../UserService
      dockerfile: Dockerfile
      target: build    

    volumes:
      - ../UserService:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro

    command: ["dotnet", "watch", "run", "--urls", "http://+:8080"]

    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - user_service_db



  showroom_service_app:
    build:
      context: ../ShowroomService
      dockerfile: Dockerfile
      target: build
    volumes:
      - ../ShowroomService:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
    command: ["dotnet", "watch", "run", "--urls", "http://+:8080"]
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - showroom_service_db