services:
  vehicle_service_db:
    image: postgres:17
    container_name: vehicle_service_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${VEHICLE_DB_USER}
      POSTGRES_PASSWORD: ${VEHICLE_DB_PASSWORD}
      POSTGRES_DB: ${VEHICLE_DB_NAME}
    ports:
      - "${VEHICLE_DB_HOST_PORT}:5432"
    volumes:
      - vehicle_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${VEHICLE_DB_USER} -d ${VEHICLE_DB_NAME}"]
      interval: 3s
      timeout: 3s
      retries: 5

  vehicle_service_app:
    image: 170anton/vehicle_service_app:latest
    container_name: vehicle_service_app
    restart: unless-stopped
    ports:
      - "${VEHICLE_APP_HOST_PORT}:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=vehicle_service_db;Port=5432;Database=${VEHICLE_APP_DB_NAME};Username=${VEHICLE_APP_DB_USER};Password=${VEHICLE_APP_DB_PASSWORD}"
    depends_on:
      vehicle_service_db:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_service
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "${PGADMIN_HOST_PORT}:80"
    volumes:
      - pgadmin_app_data:/var/lib/pgadmin
    depends_on:
      - vehicle_service_db

volumes:
  vehicle_postgres_data:
  pgadmin_app_data: