services:
  vehicle_service_app:
    build:
      context: ../VehicleService  
      dockerfile: Dockerfile
      target: build    
    
    volumes:
      - ../VehicleService:/app 
      - ~/.nuget/packages:/root/.nuget/packages:ro

    command: ["dotnet", "watch", "run", "--urls", "http://+:8080"]

    environment:
      ASPNETCORE_ENVIRONMENT: Development