services:

  # --- VEHICLE SERVICE ---

  vehicle_service_db:
    image: postgres:17
    container_name: vehicle_service_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${VEHICLE_DB_USER}
      POSTGRES_PASSWORD: ${VEHICLE_DB_PASSWORD}
      POSTGRES_DB: ${VEHICLE_DB_NAME}
    ports:
      - "${VEHICLE_DB_HOST_PORT}:5432"
    volumes:
      - vehicle_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${VEHICLE_DB_USER} -d ${VEHICLE_DB_NAME}"]
      interval: 3s
      timeout: 3s
      retries: 5

  vehicle_service_app:
    image: 170anton/vehicle_service_app:latest
    container_name: vehicle_service_app
    restart: unless-stopped
    ports:
      - "${VEHICLE_APP_HOST_PORT}:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=vehicle_service_db;Port=5432;Database=${VEHICLE_APP_DB_NAME};Username=${VEHICLE_APP_DB_USER};Password=${VEHICLE_APP_DB_PASSWORD}"
    depends_on:
      vehicle_service_db:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_service
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "${PGADMIN_HOST_PORT}:80"
    volumes:
      - pgadmin_app_data:/var/lib/pgadmin
    depends_on:
      - vehicle_service_db



  # --- USER SERVICE ---

  user_service_db:
    image: mongo:latest
    container_name: user_service_db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${USER_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${USER_DB_PASSWORD}
    ports:
      - "${USER_DB_HOST_PORT}:27017"
    volumes:
      - user_mongo_data:/data/db

  user_service_app:
    image: 170anton/user_service_app:latest
    container_name: user_service_app
    restart: unless-stopped
    ports:
      - "${USER_APP_HOST_PORT}:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MongoDbSettings__ConnectionString: "mongodb://${USER_DB_USER}:${USER_DB_PASSWORD}@user_service_db:27017"
      MongoDbSettings__DatabaseName: ${USER_APP_DB_NAME}
    depends_on:
      - user_service_db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - "${MONGO_EXPRESS_HOST_PORT}:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${USER_DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${USER_DB_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: user_service_db
    depends_on:
      - user_service_db


  # --- SHOWROOM SERVICE ---

  showroom_service_db:
    image: postgres:17
    container_name: showroom_service_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${SHOWROOM_DB_USER}
      POSTGRES_PASSWORD: ${SHOWROOM_DB_PASSWORD}
      POSTGRES_DB: ${SHOWROOM_DB_NAME}
    ports:
      - "${SHOWROOM_DB_HOST_PORT}:5432"
    volumes:
      - showroom_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SHOWROOM_DB_USER} -d ${SHOWROOM_DB_NAME}"]
      interval: 3s
      timeout: 3s
      retries: 5

  showroom_service_app:
    image: 170anton/showroom_service_app:latest
    container_name: showroom_service_app
    restart: unless-stopped
    ports:
      - "${SHOWROOM_APP_HOST_PORT}:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=showroom_service_db;Port=5432;Database=${SHOWROOM_APP_DB_NAME};Username=${SHOWROOM_APP_DB_USER};Password=${SHOWROOM_APP_DB_PASSWORD}"
    depends_on:
      showroom_service_db:
        condition: service_healthy

volumes:
  vehicle_postgres_data:
  pgadmin_app_data:
  user_mongo_data:
  showroom_postgres_data: